// Offline demo fallback dictionary of interesting 5-letter words with descriptions
const DEMO_WORDS = [
  { word: "PIXEL", hint: "The smallest single addressable element in a digital image." },
  { word: "SPACE", hint: "The boundless three-dimensional extent in which objects and events have relative position and direction." },
  { word: "SHARK", hint: "Apex ocean predator with multiple rows of teeth and a cartilaginous skeleton." },
  { word: "BRAIN", hint: "An organ of soft nervous tissue contained in the skull of vertebrates." },
  { word: "FLAME", hint: "A hot glowing body of ignited gas that is generated by something on fire." },
  { word: "PLANT", hint: "A living organism of the kind exemplified by trees, shrubs, herbs, and mosses." },
  { word: "GHOST", hint: "An apparition of a dead person which is believed to appear to the living." },
  { word: "MAGIC", hint: "The power of apparently influencing the course of events by using mysterious or supernatural forces." },
  { word: "STARS", hint: "Luminous points in the night sky which are large, remote incandescent bodies." },
  { word: "CLOCK", hint: "An instrument for measuring and recording time." },
  { word: "STORM", hint: "A violent disturbance of the atmosphere with strong winds and usually rain or snow." },
  { word: "HEART", hint: "A hollow muscular organ that pumps the blood through the circulatory system." },
  { word: "MUSIC", hint: "Vocal or instrumental sounds combined in such a way as to produce beauty of form, harmony, and expression." },
  { word: "OCEAN", hint: "A very large expanse of sea, in particular, each of the main areas of saline water." },
  { word: "DREAM", hint: "A series of thoughts, images, and sensations occurring in a person's mind during sleep." },
  { word: "CHESS", hint: "A board game for two players, each starting with 16 pieces, containing knights, rooks, and a king." },
  { word: "RIVER", hint: "A large natural stream of water flowing in a channel to the sea, a lake, or another stream." },
  { word: "FAIRY", hint: "A small imaginary being of human form that has magical powers, especially in legends." },
  { word: "SNAKE", hint: "A long limbless legless reptile, some species of which have venomous bites." },
  { word: "BREAD", hint: "Common food made of flour, water, and yeast mixed together and baked." },
  { word: "LEMON", hint: "A pale yellow oval citrus fruit with thick skin and fragrant, highly acidic juice." },
  { word: "CANDY", hint: "A sweet food made with sugar or syrup, often combined with chocolate or fruit." },
  { word: "FRUIT", hint: "The sweet and fleshy product of a tree or other plant that contains seed." },
  { word: "CLOUD", hint: "A visible mass of condensed water vapor floating in the atmosphere." },
  { word: "LIGHT", hint: "The natural agent that stimulates sight and makes things visible." },
  { word: "SOUND", hint: "Vibrations traveling through the air or another medium that can be heard." },
  { word: "EARTH", hint: "The third planet from the sun, which is the planet on which we live." },
  { word: "GLASS", hint: "A hard, brittle substance, typically transparent, made by fusing sand with soda and lime." },
  { word: "STONE", hint: "Hard solid nonmetallic mineral matter of which rock is made." },
  { word: "GRASS", hint: "Vegetation consisting of typically short plants with long, narrow leaves." },
  { word: "SWEET", hint: "Having the pleasant taste characteristic of sugar or honey." },
  { word: "SHINE", hint: "To emit or reflect light; give out a bright glow." },
  { word: "BLADE", hint: "The flat cutting edge of a knife, tool, sword, or weapon." },
  { word: "DANCE", hint: "Move rhythmically to music, typically following a set sequence of steps." },
  { word: "TIGER", hint: "A very large solitary cat with a yellow-brown coat striped with black." },
  { word: "WATER", hint: "A colorless, transparent, odorless liquid that forms the seas, lakes, and rain." },
  { word: "SMILE", hint: "A pleased, kind, or amused expression, with the corners of the mouth turned up." },
  { word: "LUNCH", hint: "A meal eaten in the middle of the day, between breakfast and dinner." },
  { word: "MOUNT", hint: "A peak, high hill, or mountain, or the act of climbing up on something." },
  { word: "GREEN", hint: "The color of emeralds, jade, or fresh growing grass." },
  { word: "WHITE", hint: "The color of fresh milk or pristine mountain snow." },
  { word: "BLACK", hint: "The very darkest color, matching charcoal or the complete absence of light." },
  { word: "SMOKE", hint: "A visible suspension of carbon particles in the air from a burning substance." },
  { word: "WAVES", hint: "Disturbances that travel through space or water, transferring energy." },
  { word: "CROWN", hint: "A circular ornamental headdress worn by a monarch as a symbol of authority." },
  { word: "PEARL", hint: "A hard, lustrous spherical mass formed within the shell of a pearl oyster." },
  { word: "BRUSH", hint: "An implement with bristles, hair, or wire, for cleaning, painting, or grooming." },
  { word: "HOUSE", hint: "A building for human habitation, especially one that is lived in by a family." },
  { word: "SHIRT", hint: "A garment for the upper body made of cotton or a similar fabric, with collar and sleeves." },
  { word: "CHAIR", hint: "A separate seat for one person, typically with four legs and a back support." }
];

const BACKEND_URL = import.meta.env.VITE_BACKEND_API;

/**
 * Fetches a random 5-letter word and hint from the backend.
 * Falls back gracefully to the local dictionary if the server is offline.
 * 
 * @returns {Promise<{ word: string, hint: string, isDemo: boolean }>}
 */
export async function fetchWordFromBackend() {
  try {

    const controller = new AbortController();

    const response = await fetch(BACKEND_URL, {
      signal: controller.signal,
      headers: {
        "Accept": "application/json",
      }
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const data = await response.json();

    // Validate response shape
    if (data && data.word && data.word.length === 5) {
      return {
        word: data.word.toUpperCase(),
        hint: data.hint || "No description provided for this word.",
      };
    }

    throw new Error("Invalid API response format");
  } catch (error) {
    console.warn("Backend fetch failed, utilizing premium offline Demo Mode. Details:", error.message);

    // Choose a random item from the list
    const randomIndex = Math.floor(Math.random() * DEMO_WORDS.length);
    const demoItem = DEMO_WORDS[randomIndex];

    return {
      word: demoItem.word.toUpperCase(),
      hint: demoItem.hint,
    };
  }
}
